############################# English ############################
[en]
languageName = "En"
title = "Orbital Web Management"
contentDir = "content/english" # content/english
weight = 1
########### footer content ##########
footer_menu_left = "Service"
footer_menu_middle = "Support"
footer_menu_right = "Support"
footer_content = "Orbital Web is a service dedicated to website development, hosting and maintenance."
# copyright
copyright = "A Service by Richard Martin"